name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]

[[depends-on]]
noise_nugget_sdk = "*"

[[pins]]
noise_nugget_sdk = { path='..' }

[build-profiles]
noise_nugget_sdk = "development"
# noise_nugget_sdk = "release"

[[depends-on]]
tresses = "~0.1.0-dev"
[[pins]]
tresses = { url='git@github.com:wee-noise-maker/tresses.git' }
