name = "noise_nugget_sdk"
description = "Ada Software Development Kit for the Noise Nugget"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[[depends-on]]
rp2040_hal = "^2.3.0"
midi = "~0.2.0"
gnat_arm_elf = "*"

[configuration.values]
rp2040_hal.Flash_Chip = "w25qxx"

[gpr-set-externals]
BBQUEUE_COMPILE_CHECKS = "disabled"
BBQUEUE_RUNTIME_CHECKS = "disabled"
BBQUEUE_STYLE_CHECKS   = "disabled"
BBQUEUE_CONTRACTS      = "disabled"
BBQUEUE_BUILD_MODE     = "optimize"

[[pins]]
rp2040_hal = { url="https://github.com/JeremyGrosser/rp2040_hal" }
