name = "noise_nugget_sdk"
description = "Ada Software Development Kit for the Noise Nugget"
version = "1.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[[depends-on]]
rp2040_hal = "~2.4.1"
midi = "^1.0.0"
gnat_arm_elf = "*"

[configuration.variables]
System_Clock= {type = "Enum", values = ["SYS_48MHz", "SYS_125MHz", "SYS_133MHz",
                                        "SYS_250MHz"], default = "SYS_133MHz"}

[configuration.values]
rp2040_hal.Flash_Chip = "w25qxx"

[[pins]]
rp2040_hal = { url="https://github.com/JeremyGrosser/rp2040_hal", commit="ef10b88494060944243f7cf0d12b3a02719c9d4b" }
